### ISSUE TITLE
desgin home page

### ISSUE THREAD

**Issue by abinashnepali** [abinashnepali/abinashnepali.github.io#1]
Hi I am new, I want your help for creating homepage.

**Comment by egin10** [comment]
i want to pull request here, but how to do it ? it can't done

**Comment by Priyansh2** [comment]
@abinashnepali what kind of homepage do you want and for what . I mean  Are you building a website or an app ? What this homepage is about ? What features do you want on this page ? Can you elaborate on this issue .
